### ISSUE TITLE
Prism's Eye bugs

### ISSUE THREAD

**Issue by JavidPack** [JavidPack/CrystiliumMod#8]
From: https://forums.terraria.org/index.php?threads/crystilium-mod.44558/page-37#post-1891728

Found issues with Prism's Eye
-It doesn't use sentry slots
-it doesn't last very long for a sentry
-it targets target dummies
-it seems to refuse pointing straight left, and will turn the long way around if its target is to its left and crosses a line going from its center to straight left
this is what I mean

**Comment by qwerty3-14** [comment]
I've made a pull request that fixes these issues

**Comment by JavidPack** [comment]
Fixed in 3a0b09e
